"use client";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

import {
  Brain,
  Mic,
  Puzzle,
  Route,
  ScanSearch,
  ShieldCheck,
  Activity,
  HeartPulse,
} from "lucide-react";

export default function ExpertSection() {
  return (
    <section className="w-full py-20 px-4">

      <div className="max-w-6xl mx-auto">

        <Card className="rounded-[32px] shadow-2xl border border-slate-200 bg-white/95 backdrop-blur-md overflow-hidden">

          {/* HEADER */}
          <div className="bg-gradient-to-r from-sky-100 via-blue-50 to-cyan-100 p-10 border-b">

            <div className="flex items-center justify-center gap-4 mb-4">

              <div className="h-16 w-16 rounded-full bg-white shadow-md flex items-center justify-center">
                <Brain className="h-9 w-9 text-sky-600" />
              </div>

              <div>

                <h1 className="text-5xl font-extrabold text-slate-900">
                  Final Cognitive Snapshot
                </h1>

                <p className="text-lg text-slate-600 mt-2">
                  AI-powered combined cognitive screening analysis generated by Neuro Nova
                </p>

              </div>

            </div>

          </div>

          <CardContent className="p-8 md:p-12 space-y-10">

            {/* OVERALL SCORE */}
            <div className="grid md:grid-cols-3 gap-6">

              <div className="rounded-3xl bg-gradient-to-br from-sky-500 to-cyan-500 text-white p-8 shadow-lg">

                <p className="text-lg font-medium opacity-90">
                  Overall Cognitive Score
                </p>

                <h2 className="text-6xl font-extrabold mt-3">
                  82%
                </h2>

                <p className="mt-4 text-sky-50 leading-7">
                  Combined score generated using weighted AI analysis across all screening modules.
                </p>

              </div>

              <div className="rounded-3xl bg-gradient-to-br from-green-500 to-emerald-500 text-white p-8 shadow-lg">

                <p className="text-lg font-medium opacity-90">
                  Risk Classification
                </p>

                <h2 className="text-5xl font-extrabold mt-3">
                  Low Risk
                </h2>

                <p className="mt-4 text-green-50 leading-7">
                  Cognitive indicators remain within healthy and expected range.
                </p>

              </div>

              <div className="rounded-3xl bg-gradient-to-br from-purple-500 to-fuchsia-500 text-white p-8 shadow-lg">

                <p className="text-lg font-medium opacity-90">
                  AI Confidence Level
                </p>

                <h2 className="text-5xl font-extrabold mt-3">
                  94%
                </h2>

                <p className="mt-4 text-purple-50 leading-7">
                  High-confidence cognitive interpretation based on multi-module analysis.
                </p>

              </div>

            </div>

            {/* MODULE SCORES */}
            <div>

              <h2 className="text-3xl font-bold text-slate-900 mb-6">
                Individual Module Performance
              </h2>

              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5">

                <div className="rounded-3xl bg-sky-50 border border-sky-100 p-6 shadow-sm">

                  <div className="flex items-center justify-between mb-4">
                    <Mic className="h-8 w-8 text-sky-600" />
                    <span className="text-3xl font-bold text-sky-700">
                      84%
                    </span>
                  </div>

                  <h3 className="font-bold text-xl text-slate-900">
                    Voice Analysis
                  </h3>

                  <p className="text-slate-600 mt-2 leading-7">
                    Speech rhythm, fluency, hesitation patterns, and lexical diversity were analyzed.
                  </p>

                </div>

                <div className="rounded-3xl bg-green-50 border border-green-100 p-6 shadow-sm">

                  <div className="flex items-center justify-between mb-4">
                    <Puzzle className="h-8 w-8 text-green-600" />
                    <span className="text-3xl font-bold text-green-700">
                      79%
                    </span>
                  </div>

                  <h3 className="font-bold text-xl text-slate-900">
                    Memory Game
                  </h3>

                  <p className="text-slate-600 mt-2 leading-7">
                    Recall ability, pattern recognition, and short-term memory efficiency were evaluated.
                  </p>

                </div>

                <div className="rounded-3xl bg-yellow-50 border border-yellow-100 p-6 shadow-sm">

                  <div className="flex items-center justify-between mb-4">
                    <ScanSearch className="h-8 w-8 text-yellow-600" />
                    <span className="text-3xl font-bold text-yellow-700">
                      86%
                    </span>
                  </div>

                  <h3 className="font-bold text-xl text-slate-900">
                    Stroop Test
                  </h3>

                  <p className="text-slate-600 mt-2 leading-7">
                    Attention control, cognitive flexibility, and interference handling were assessed.
                  </p>

                </div>

                <div className="rounded-3xl bg-purple-50 border border-purple-100 p-6 shadow-sm">

                  <div className="flex items-center justify-between mb-4">
                    <Route className="h-8 w-8 text-purple-600" />
                    <span className="text-3xl font-bold text-purple-700">
                      75%
                    </span>
                  </div>

                  <h3 className="font-bold text-xl text-slate-900">
                    Maze Navigation
                  </h3>

                  <p className="text-slate-600 mt-2 leading-7">
                    Visuospatial planning, navigation efficiency, and reaction behavior were measured.
                  </p>

                </div>

              </div>

            </div>

            {/* AI SUMMARY */}
            <div className="rounded-[28px] bg-gradient-to-br from-slate-50 to-slate-100 border border-slate-200 p-10 shadow-inner">

              <div className="flex items-center gap-4 mb-5">

                <div className="h-14 w-14 rounded-full bg-white shadow flex items-center justify-center">
                  <Activity className="h-7 w-7 text-slate-700" />
                </div>

                <div>

                  <h2 className="text-3xl font-bold text-slate-900">
                    AI Cognitive Interpretation
                  </h2>

                  <p className="text-slate-500">
                    Generated using Gemini AI cognitive analysis
                  </p>

                </div>

              </div>

              <p className="text-lg leading-9 text-slate-700">
                Neuro Nova observed stable cognitive functioning with healthy memory retention,
                speech fluency, and attentional control. The participant demonstrated strong
                response accuracy across multiple modules with only mild fluctuations in
                processing speed during complex tasks. Overall interaction behavior suggests
                balanced cognitive performance within expected healthy ranges.
              </p>

            </div>

            {/* WELLNESS */}
            <div className="grid md:grid-cols-2 gap-6">

              <div className="rounded-3xl bg-blue-50 border border-blue-100 p-8">

                <div className="flex items-center gap-3 mb-4">

                  <HeartPulse className="h-8 w-8 text-blue-600" />

                  <h2 className="text-2xl font-bold text-slate-900">
                    Cognitive Wellness Tips
                  </h2>

                </div>

                <ul className="space-y-4 text-slate-700 leading-7">

                  <li>
                    • Engage in regular mental stimulation activities such as puzzles and reading
                  </li>

                  <li>
                    • Maintain consistent sleep and hydration patterns
                  </li>

                  <li>
                    • Participate in social interactions and memory exercises regularly
                  </li>

                  <li>
                    • Practice mindfulness and stress management techniques
                  </li>

                </ul>

              </div>

              <div className="rounded-3xl bg-emerald-50 border border-emerald-100 p-8">

                <div className="flex items-center gap-3 mb-4">

                  <ShieldCheck className="h-8 w-8 text-emerald-600" />

                  <h2 className="text-2xl font-bold text-slate-900">
                    Neuro Nova AI Insights
                  </h2>

                </div>

                <ul className="space-y-4 text-slate-700 leading-7">

                  <li>
                    • Multilingual AI-powered cognitive screening support
                  </li>

                  <li>
                    • Real-time behavioral and interaction analysis
                  </li>

                  <li>
                    • AI-generated compassionate cognitive summaries
                  </li>

                  <li>
                    • Secure Firebase-based data management and reporting
                  </li>

                </ul>

              </div>

            </div>

          </CardContent>

        </Card>

      </div>

    </section>
  );
}